version: "3.9"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: pa$$word
    volumes:
      - db_data:/var/lib/postgresql/data/
      - backup_data:/backups

volumes:
  db_data:
  backup_data:
