---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
    - name: db
      protocol: TCP
      port: {{ .Values.service.targetPort.db }}
      targetPort: {{ .Values.service.targetPort.db }}
  type: ClusterIP