---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name}}-{{.Values.metadata.pv.name}}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  capacity:
    storage: 1G
  hostPath:
    path: /data/pv
