Vagrant.configure(2) do |config| 
  config.vm.provider :virtualbox
  (1..3).each do |i|
    config.vm.define "Node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.network "private_network", ip: "192.168.56.2#{i}"
      node.vm.disk :disk, size: "30GB"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./ansible/main_ansible.yml"
  end
end
