apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: netologyQbec
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://192.168.49.2:8443

    stage:
      defaultNamespace: stage
      server: https://192.168.49.2:8443

    prod:
      defaultNamespace: prod
      server: https://192.168.49.2:8443
      includes:
        - nginx
  vars: {}
