---
all:
  vars:
    ansible_connection: ssh
    ansible_user: centos
  hosts:
    ela-instance:
      ansible_host: 178.154.202.58
    kib-instance:
      ansible_host: 178.154.205.40
    log-instance:
      ansible_host: 178.154.202.58
    fb-instance:
      ansible_host: 178.154.206.200

elasticsearch:
  hosts:
    ela-instance:

kibana:
  hosts:
    kib-instance:

logstash:
  hosts:
    log-instance:

filebeat:
  hosts:
    fb-instance: